changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main
  - develop
  - origin/develop
  - upstream/develop

compressionLevel: mixed

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
