nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.2.1.cjs

changesetBaseRefs:
  - 'master'
  - 'origin/master'
  - 'upstream/master'
  - 'main'
  - 'origin/main'
  - 'upstream/main'
  - 'develop'
  - 'origin/develop'
  - 'upstream/develop'
