changesetBaseRefs:
  - master
  - origin/master
  - upstream/master
  - main
  - origin/main
  - upstream/main
  - develop
  - origin/develop
  - upstream/develop

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs
