# ------------------------------------
# This is the base file that is used in all pipelines
# Please, DO NOT CHANGE it
# Change 'ci-variables.yml' instead
# ------------------------------------
variables:
  BUILD_NUMBER: 0.1.$(Build.BuildId)
  REACT_APP_BUILD_NUMBER: 0.1.$(Build.BuildId)
  solution: 'webapi/MccSoft.TemplateApp.sln'
  project: 'webapi/src/MccSoft.TemplateApp.App/MccSoft.TemplateApp.App.csproj'
