# ------------------------------------
# This is the base file that is used in all pipelines
# Please, DO NOT CHANGE it
# Change 'base.partial.yml' instead
# ------------------------------------
variables:
  BUILD_NUMBER: 0.1.$(Build.BuildId)
  REACT_APP_BUILD_NUMBER: 0.1.$(Build.BuildId)
  solution: 'webapi/MccSoft.TemplateApp.sln'
  project: 'webapi/src/MccSoft.TemplateApp.App/MccSoft.TemplateApp.App.csproj'

  # General
  DISABLE_BUILD: false
  DISABLE_TESTS: false
  # -----------

  # Storybook
  ENABLE_STORYBOOK: true
  RUN_STORYBOOK_TESTS_AFTER_BUILD: false
  RUN_STORYBOOK_TESTS_PARALLEL_BUILD: true
  # -----------

  # e2e
  ENABLE_E2E: true
  DEPLOY_IF_E2E_FAILS: true
  # -----------

  # Deployment
  DOCKER_TAG: latest
  ENABLE_DEPLOY: true
  ENABLE_TAG_SOURCES: false
  DEPLOY_IF_STORYBOOK_FAILS: false
  # -----------
