version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - plugins.security.ssl.http.enabled=false
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - "VIRTUAL_HOST=https://${VIRTUAL_HOST}:9200 -> :9200"
      - "VIRTUAL_HOST2=http://${VIRTUAL_HOST}:9201 -> :9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      - opensearch-net
    restart: always

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - plugins.security.ssl.http.enabled=false
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
    restart: always

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    environment:
      - plugins.security.ssl.http.enabled=false
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
      - "VIRTUAL_HOST=https://${VIRTUAL_HOST} -> :5601"
    networks:
      - opensearch-net
    restart: always

  nginx-proxy:
    image: mesudip/nginx-proxy
    container_name: nginx-proxy_logs
    restart: always
    networks:
      - opensearch-net
    ports:
      - "80:80"
      - "443:443"
      - "9201:9201"
      - "9200:9200"
    volumes:
      - ssl:/etc/ssl
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  opensearch-data1:
  opensearch-data2:
  ssl:
  dhparam:

networks:
  opensearch-net:
    name: frontend
