steps:
  - publish: './publish'
    artifact: 'publish'

  - script: |
      docker login $(DOCKER_REGISTRY) -u $(DOCKER_USER) -p $(DOCKER_TOKEN)
    displayName: 'Authenticate at Container Registry'

  - task: Docker@2
    condition: succeeded()
    inputs:
      repository: $(DOCKER_REGISTRY)
      command: 'buildAndPush'
      Dockerfile: 'publish/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/publish'
      ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        tags: |
          $(BUILD_NUMBER)
          latest
      ${{ else }}:
        tags: |
          $(BUILD_NUMBER)
    displayName: 'build and push docker image'
