import * as Types from './query-client.types';
export * from './query-client.types';

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import type { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export * as TestApiClient from './query-client/TestApiClient';



export * as ProductClient from './query-client/ProductClient';



export * as SignUrlClient from './query-client/SignUrlClient';



export * as TestDataClient from './query-client/TestDataClient';



export * as VersionClient from './query-client/VersionClient';





import { addResultTypeFactory } from './query-client/helpers';
export { setBaseUrl, getBaseUrl } from './query-client/helpers';
export { setAxiosFactory, getAxios } from './query-client/helpers';


//-----PersistorHydrator.File-----

//-----/PersistorHydrator.File----